theme: minima
title: Welcome to Milo on GitHub
author: milodubois
description: > # this means to ignore newlines until "baseurl:"
  This simple blog, by Milo, is a GitHub page made with Jekyll as a product of the GitHub Pages tutorial.

# social links
github_username:  milodubois

show_excerpts: true # set to false to remove excerpts on the homepage
